project_name: ExampleProject
service_name: "{{ project_name|lower }}"
gitdeploy_version: "1.0.6"
python: python3.7
service_port: 5000
application_user: apps

playbooks:
  - playbook.deploy.yml

# these will be merged with deployment-specific env into variable init_env
init_env_common:
  PROJECT_NAME: "{{ project_name }}"


install_root: "/home/apps/sites"
deploy_dir: "{{ install_root }}/{{ project_name }}"
application_dir: "{{ deploy_dir }}/examples/flaskproject"
env_file: "{{ deploy_dir }}/.env"
envrc_file: "{{ deploy_dir }}/.envrc"
virtualenv: "{{ deploy_dir }}/.venv"
project_repo: "git@github.com:NUKnightLab/git-deploy.git"
requirements_file: "{{ deploy_dir }}/requirements.txt"
wsgi_application: "core.wsgi:application"
