project_name: ExampleProject
service_name: "{{ project_name|lower }}"
gitdeploy_version: "1.0.6"
python: python3.7
service_port: 5000


### Set these variables ###

application_user: # user who runs applications
application_group: # group, usually the same as the user
install_root: # path on remote to where all your applications go
exec_path: # may be needed if python is not on the path, alternatively set the full path to python above
ssl_certs: # See the nginx role for details.

##########################

playbooks:
  - playbook.deploy.yml

# these will be merged with deployment-specific env into variable init_env
init_env_common:
  PROJECT_NAME: "{{ project_name }}"


deploy_dir: "{{ install_root }}/{{ project_name }}"
application_dir: "{{ deploy_dir }}"
env_file: "{{ deploy_dir }}/.env"
envrc_file: "{{ deploy_dir }}/.envrc"
virtualenv: "{{ deploy_dir }}/.venv"
project_repo: "git@github.com:NUKnightLab/git-deploy-example.git"
requirements_file: "{{ deploy_dir }}/requirements.txt"
wsgi_application: "core.wsgi:application"
